#!/usr/bin/env python3
"""Generates test_cases.h: known-good (input, sorted) pairs for the C++ test runner.

Run this whenever you want to regenerate the fixtures:
    python3 generate_test_cases.py
"""
import random

OUTPUT = "test_cases.h"


def make_case(name, n, seed, kind="random"):
    rng = random.Random(seed)
    if kind == "random":
        arr = [rng.randint(0, 10_000_000) for _ in range(n)]
    elif kind == "duplicates":
        # small value range forces lots of repeated digits/keys
        arr = [rng.randint(0, 5) for _ in range(n)]
    elif kind == "sorted":
        arr = sorted(rng.randint(0, 10_000_000) for _ in range(n))
    elif kind == "reverse_sorted":
        arr = sorted((rng.randint(0, 10_000_000) for _ in range(n)), reverse=True)
    elif kind == "constant":
        arr = [42] * n
    elif kind == "large_values":
        # near u64 range, to exercise the high-order bytes
        arr = [rng.randint(0, 2**63 - 1) for _ in range(n)]
    else:
        raise ValueError(f"unknown kind {kind}")

    expected = sorted(arr)
    return name, arr, expected


cases = [
    make_case("n10_random", 10, 1),
    make_case("n17_random", 17, 42),  # matches the original hand-written sample size
    make_case("n25_duplicates", 25, 2, kind="duplicates"),
    make_case("n50_random", 50, 3),
    make_case("n100_random", 100, 4),
    make_case("n100_sorted", 100, 5, kind="sorted"),
    make_case("n250_reverse_sorted", 250, 6, kind="reverse_sorted"),
    make_case("n250_constant", 250, 7, kind="constant"),
    make_case("n500_random", 500, 8),
    make_case("n1000_random", 1000, 9),
    make_case("n1000_large_values", 1000, 10, kind="large_values"),
]


def fmt(arr):
    return "{" + ",".join(str(x) for x in arr) + "}"


with open(OUTPUT, "w") as f:
    f.write("// Auto-generated by generate_test_cases.py. Do not edit by hand.\n")
    f.write("#pragma once\n#include <vector>\n#include <string>\n#include <cstdint>\n\n")
    f.write("struct TestCase { std::string name; std::vector<uint64_t> input; std::vector<uint64_t> expected; };\n\n")
    f.write("inline std::vector<TestCase> GetTestCases() {\n    return {\n")
    for name, arr, expected in cases:
        f.write(f'        TestCase{{"{name}", {fmt(arr)}, {fmt(expected)}}},\n')
    f.write("    };\n}\n")

print(f"wrote {len(cases)} cases to {OUTPUT}")
